POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "Alice",
    "password": "topsecret"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "Alice",
    "password": "falsepin"
}

###
GET http://localhost:3000/auth/me


### 
GET http://localhost:3000/auth/me
authorization : Bearer falsetokenfalse


### 
GET http://localhost:3000/auth/me
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWxpY2UiLCJpYXQiOjE3Mjg5Mzc2ODAsImV4cCI6MTcyOTAyNDA4MH0.-t4PganBT6mGRIxw-5vlDZwpH8t6QL6qPBMwQVJaPXs

### 
GET http://localhost:3000/auth-v2/me